apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cert-manager
spec:
  destination:
    name: ""
    namespace: certmanager
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://charts.jetstack.io"
    targetRevision: v1.15.3
    chart: cert-manager
    helm:
      parameters:
        - name: crds.enabled
          value: "true"
        - name: dnsPolicy
          value: "None"
        - name: podDnsConfig.nameservers[0]
          value: "1.1.1.1"
        - name: podDnsConfig.nameservers[1]
          value: "8.8.8.8"
        - name: dns01RecursiveNameservers
          value: "1.1.1.1"
  sources: []
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kasper.kn.nielsen@jppol.dk
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx-public
