apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: ingress-nginx-public
spec:
  destination:
    name: ""
    namespace: ingress-nginx
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.11.2
    chart: ingress-nginx
    helm:
      values: |
        nameOverride: ingress-nginx-public
        controller:
          ingressClassByName: true
          kind: Deployment
          replicaCount: 1
          allowSnippetAnnotations: true
          # extraArgs:
          #   default-ssl-certificate: "kube-system/cert-wildcard-livahealthcare-com"

          config:
            use-proxy-protocol: "true"
          podAnnotations:
            linkerd.io/inject: false

          # # Ensures ingress-nginx is only deployed to static nodes with label 'node-type': 'static' (non karpenter spot)
          # affinity:
          #   nodeAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #       nodeSelectorTerms:
          #       - matchExpressions:
          #         - key: node-type
          #           operator: In
          #           values:
          #           - static

          ingressClassResource:
            name: nginx-public
            enabled: true
            default: false
            controllerValue: "k8s.io/ingress-nginx-public"

          metrics:
            port: 10254
            portName: metrics
            # if this port is changed, change healthz-port: in extraArgs: accordingly
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "10254"
              # -- Labels to be added to the metrics service resource
              labels: {}
              # clusterIP: ""

          service:
            external:
              enabled: true
            internal:
              enabled: false
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "external"
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
              service.beta.kubernetes.io/aws-load-balancer-name: "ingress-nginx-public"
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
              service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
              service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: proxy_protocol_v2.enabled=true

  sources: []
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
