apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://kubernetes-sigs.github.io/metrics-server/"
    targetRevision: 3.12.1
    chart: metrics-server
  sources: []
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
