apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: grafana-loki
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      path: ""
      targetRevision: 6.12.0
      chart: loki
      helm:
        valueFiles:
          - $values/grafana-loki/values.yaml
    - repoURL: https://github.com/Lynetk/eks-argo-config.git
      targetRevision: main
      ref: values
