apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: grafana
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: "8.5.1"
    chart: grafana
    helm:
      values: |
        admin:
          existingSecret: "grafana-admin-credentials"
          userKey: admin-user
          passwordKey: admin-password
        persistence:
          type: pvc
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 10Gi
        ingress:
          enabled: true
          ingressClassName: nginx-public
          # Values can be templated
          annotations:
            kubernetes.io/ingress.class: nginx-private

          labels: {}
          path: /

          # pathType is only for k8s >= 1.1=
          pathType: Prefix

          hosts:
            - grafana.jppol.click
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server
                access: proxy
                isDefault: true
              - name: Loki
                type: loki
                url: http://grafana-loki-gateway
                access: proxy
                isDefault: false
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
        dashboards:
          default:
            node-exporter:
              gnetId: 1860
              revision: 37
              datasource: Prometheus
            ingress-nginx:
              gnetId: 21336
              revision: 1
              datasource: Prometheus
            prometheus-stats:
              gnetId: 2
              revision: 2
              datasource: Prometheus
  sources: []
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
