apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: homepage
spec:
  destination:
    namespace: idp-custom
    server: https://kubernetes.default.svc
  project: idp-project
  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts/
    targetRevision: 2.0.1
    helm:
      values: |
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt"
            ingressClassName: nginx-public
            hosts:
              - host: start.jppol.click
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                - start.jppol.click
                secretName: start-jppol-click
        config:
          services:
            - IDP:
              - ArgoCD
                href: https://argocd.jppol.click
                description: GitOPS
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
