apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
spec:
  destination:
    name: ""
    namespace: idp-custom
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "http://jameswynn.github.io/helm-charts"
    targetRevision: 2.0.1
    chart: homepage
    helm:
      values: |
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            ingressClassName: nginx-public
            hosts:
              - host: start.jppol.click
              paths:
                - path: /
                  pathType: Prefix
            tls:
              - hosts:
                - start.jppol.click
                secretName: start-jppol-click
  sources: []
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
