apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: homepage
spec:
  destination:
    namespace: idp-custom
    server: https://kubernetes.default.svc
  project: idp-project
  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts/
    targetRevision: 2.0.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
