apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: idp/grafana-admin
      versionId: 5d5539f0-cbf3-4196-a77e-5781ad3dfa6c
