apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: crossplane
spec:
  destination:
    name: ""
    namespace: crossplane-system
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://charts.crossplane.io/stable"
    targetRevision: 1.17.0
    chart: crossplane
    helm:
      values: |
        provider:
          packages: {
            xpkg.upbound.io/crossplane-contrib/provider-aws:v0.49.1
          }
  sources: []
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
