apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: "8.5.1"
    chart: grafana
    helm:
      values: |
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server
                access: proxy
                isDefault: true
              - name: Loki
                type: loki
                url: http://grafana-loki-gateway
                access: proxy
                isDefault: false
          dashboards:
            default:
              node-exporter:
                url: https://raw.githubusercontent.com/rfmoz/grafana-dashboards/master/prometheus/node-exporter-full.json
              prometheus-stats:
                gnetId: 2
                revision: 2
                datasource: Prometheus
  sources: []
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
