apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: 0.7.0
    chart: alloy
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
