apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: 6.12.0
    chart: loki
    helm:
      valueFiles:
        - simple-scalable-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
